GET http://localhost:3000/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwic3ViIjoiMDNkODdmMTItMjJhZi00YTBmLWJlYjEtMWQxZDA1YjkwOGExIiwicm9sZXMiOlt7ImlkIjoyLCJuYW1lIjoiQURNSU4ifV0sImlhdCI6MTc0NTg2NDQ0MiwiZXhwIjoxNzQ1OTUwODQyfQ.tnzBlgToTyDCNFoJTMblQqPpRgg_vi6zcZS8gcjvqWk
